Add previous branch step

diff --git a/.github/workflows/4_builderpackage_manager.yml b/.github/workflows/4_builderpackage_manager.yml
--- a/.github/workflows/4_builderpackage_manager.yml
+++ b/.github/workflows/4_builderpackage_manager.yml
@@ -229,6 +229,44 @@ jobs:
 
           sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
 
+      - name: Get previous version from Git
+        run: |
+          TAGS=$(git tag --list "v4.[0-9]*.[0-9]*")
+          BRANCHES=$(git branch -r | grep "origin/4\.[0-9]\+\.[0-9]\+$" | sed 's|origin/||' | sed 's/^[ \t]*//;s/[ \t]*$//')
+
+          CURRENT_VERSION="${TAG}"
+          echo "CURRENT_VERSION=$CURRENT_VERSION"
+
+          MAJOR_MINOR=$(echo "$CURRENT_VERSION" | grep -oE '[0-9]+\.[0-9]+')
+          PATCH=$(echo "$CURRENT_VERSION" | grep -oE '[0-9]+$')
+
+          if [[ "$PATCH" == "0" ]]; then
+              MAJOR=$(echo "$MAJOR_MINOR" | cut -d'.' -f1)
+              MINOR=$(echo "$MAJOR_MINOR" | cut -d'.' -f2)
+              PREVIOUS_MAJOR_MINOR="$MAJOR.$((MINOR - 1))"
+
+              LATEST_TAG=$(echo "$TAGS" | grep -E "^v${PREVIOUS_MAJOR_MINOR}\.[0-9]+$" | sed 's/^v//' | sort -V | tail -1)
+              LATEST_BRANCH=$(echo "$BRANCHES" | grep -E "^${PREVIOUS_MAJOR_MINOR}\.[0-9]+$" | sort -V | tail -1)
+          else
+              LATEST_TAG=$(echo "$TAGS" | grep -E "^v${MAJOR_MINOR}\.[0-9]+$" | sed 's/^v//' | grep -B1 "^$CURRENT_VERSION$" | head -n1)
+              LATEST_BRANCH=$(echo "$BRANCHES" | grep -E "^${MAJOR_MINOR}\.[0-9]+$" | grep -B1 "^$CURRENT_VERSION$" | head -n1)
+          fi
+
+          PREVIOUS_VERSION=$(printf "$LATEST_TAG\n$LATEST_BRANCH" | sort -V | tail -1)
+
+          if [[ -z "$PREVIOUS_VERSION" ]]; then
+              echo "Error: No previous version found!"
+              exit 1
+          fi
+
+          echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
+          echo "Previous version selected: $PREVIOUS_VERSION"
+
+      - name: Download docker image for previous version
+        run: |
+          echo "TAG=${{ env.PREVIOUS_VERSION }}" >> $GITHUB_ENV
+          bash $GITHUB_WORKSPACE/.github/actions/ghcr-pull-and-push/pull_image_from_ghcr.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.actor}} $CONTAINER_NAME ${{ env.PREVIOUS_VERSION }}
+
       - name: Upload package to GitHub
         if: always()
         uses: actions/upload-artifact@v4
