Add upgrade steps

diff --git a/.github/workflows/4_builderpackage_manager.yml b/.github/workflows/4_builderpackage_manager.yml
--- a/.github/workflows/4_builderpackage_manager.yml
+++ b/.github/workflows/4_builderpackage_manager.yml
@@ -263,6 +263,58 @@ jobs:
           echo "PREVIOUS_VERSION=$PREVIOUS_VERSION" >> $GITHUB_ENV
           echo "Previous version selected: $PREVIOUS_VERSION"
 
+      - name: Install previous version of Wazuh manager
+        working-directory: packages
+        run: |
+          TESTS_PATH=$GITHUB_WORKSPACE/.github/actions/test-install-components/
+
+          echo "Building previous version package: ${{ env.PREVIOUS_VERSION }}"
+          bash generate_package.sh -a ${{ env.ARCH }} --tag ${{ env.PREVIOUS_VERSION }} --system ${{ inputs.system }} $FLAGS
+
+          echo "Available packages in /tmp:"
+          find /tmp -name "wazuh-manager*${{ inputs.system }}"
+
+          # Start the container with the previous version
+          CONTAINER_ID=$(sudo docker run -d -v $TESTS_PATH/:/tests -v /tmp/:/packages -v /var/ossec:/var/ossec \
+            --entrypoint '/bin/sh' $CONTAINER_NAME:${{ env.PREVIOUS_VERSION }} -c "tail -f /dev/null")
+
+          echo "Installing previous version of Wazuh manager: ${{ env.PREVIOUS_VERSION }}"
+          echo "Available packages in the container:"
+
+          sudo docker exec $CONTAINER_ID ls -l /packages/
+          sudo docker exec $CONTAINER_ID /tests/install_component.sh "wazuh-manager-${{ env.PREVIOUS_VERSION }}.deb" manager
+
+          if grep -iq " installed.*wazuh-manager" /tmp/status.log ; then
+            echo "Previous version installed successfully."
+          else
+            echo "Failed to install previous version."
+            sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
+            exit 1
+          fi
+          echo "CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
+
+      - name: Test upgrade to latest version
+        run: |
+          if [ -z "${{ env.CONTAINER_ID }}" ] || [ -z "${{ env.PACKAGE_NAME }}" ]; then
+            echo "No container ID or package name found!"
+            exit 1
+          fi
+
+          echo "Upgrading Wazuh manager from previous version to latest..."
+
+          sudo docker exec $CONTAINER_ID chmod +x /tests/upgrade_component.sh
+          sudo docker exec $CONTAINER_ID /tests/upgrade_component.sh $PACKAGE_NAME manager
+
+          if grep -iq " upgraded.*wazuh-manager" /tmp/status.log ; then
+            echo "Upgrade successfully."
+          else
+            echo "The upgrade could not be completed."
+            sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
+            exit 1;
+          fi
+
+          sudo docker stop $CONTAINER_ID && sudo docker rm $CONTAINER_ID
+
       - name: Download docker image for previous version
         run: |
           echo "TAG=${{ env.PREVIOUS_VERSION }}" >> $GITHUB_ENV
